### PR TITLE
created an emtpy page with the input box styled exactly like todomvc

### LINKED ISSUE #4: Create an emtpy page with the input box styled exactly like TodoMVC
Should look like: 
Because you will not have any tasks entered yet, you can skip styling "entered tasks" for now. 

Image

### PR DESCRIPTION
**Pull request by BimbaMan**

### CODE REVIEW

**Comment by smaskalik** [comment]
@BimbaMan can you merge https://github.com/BimbaMan/TODOs_ReactProject/pull/6 to main and then merge main into `4-create-an-emtpy-page-with-the-input-box-styled-exactly-like-todomvc` branch? This way I would only see changes for this task.

**Comment by BimbaMan** [comment]
I hope I did everything right. You can check the changes in the second to last commit

**Comment by smaskalik** [comment]
> I hope I did everything right. You can check the changes in the second to last commit

Not exactly 😄 , your PR should show only the changes that are not in the `main` branch. Can you try merging `main` into this branch?

**Comment by BimbaMan** [comment]
Sorry, I accidentally merged this pull request. I'll create another pull request and fix all now

**Pull request merged**
